version: '3.4'

services:
  qbank.questions.webapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_HTTPS_PORT=44313
    ports:
      - "62779:80"
      - "44313:443"